# -*- coding: utf-8 -*-
"""Titanic_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jYLXfV-m1y8HfNC_sirXjgsIkzT1FALP
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv("train.csv")
print(df.shape)

print(df["Survived"].value_counts())
print(df.groupby("Sex")["Survived"].mean())

sns.barplot(data=df, x="Sex", y="Survived")
plt.title("Survival Rate by Sex")
plt.ylabel("Survival Rate")
plt.show()

sns.barplot(data=df, x="Pclass", y="Survived")
plt.title("Survival Rate by Passenger Class")
plt.ylabel("Survival Rate")
plt.show()

df["Age"] = df["Age"].fillna(df["Age"].median())
sns.boxplot(data=df, x="Survived", y="Age")
plt.title("Age Distribution by Survival")
plt.show()

